services:
  # MySQL DB Service
  clouddb:
    #build:
      #context: .
    image: mysql:8.0.37
    container_name: clouddb
    ports:
      - "3306:3306"
    volumes:
      - clouddbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=./variables.env
      - MYSQL_DATABASE=account

  # phpmyadmin to Manage MySQL DB
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=clouddb
      - PMA_USER_FILE=./variables.env
      - PMA_PASSWORD_FILE=./variables.env
    depends_on:
      - clouddb

volumes:
  clouddbdata: