services:
  # MySQL DB Service
  clouddb:
    build:
      context: .
    image: mysql
    container_name: clouddb
    ports:
      - "3306:3306"
    volumes:
      - clouddbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  # phpmyadmin to Manage MySQL DB
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=clouddb
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - clouddb

volumes:
  clouddbdata: